version: '3'
services:
  nginx:
    image: nginx:1.19-alpine
    network_mode: host
    volumes:
      - ./certs:/data/nginx/certs
      - ./nginx:/etc/nginx/conf.d
  spring-boot:
    image: "aghimagemanager/image_manager"
    ports:
      - "8080:8080"
    container_name: spring-boot
    restart: always
    volumes:
      - /logs:/logs
      - /dump:/dump
      - /data:/data
    environment:
      - SPRING_PROFILES_ACTIVE=abc
      - JAVA_OPTS=-Xloggc:/data/gc.log
    networks:
      - edge

networks:
  edge: {}