version: '3'
services:
  spring-boot:
    image: "aghimagemanager/image_manager"
    ports:
      - "8080:8080"
    container_name: spring-boot
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
  local_redis:
    image: "redis"
    ports:
      - "6379:6379"
    container_name: local_redis