version: '3'
services:
  spring-boot:
    image: "aghimagemanager/image_manager"
    ports:
      - "8080:8080"
    container_name: spring-boot
    volumes:
      - /logs:/logs
      - /dump:/dump
    environment:
      - SPRING_PROFILES_ACTIVE=abc
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 400M
        reservations:
          cpus: 0.30
          memory: 200M
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=14d"
      - "--storage.tsdb.retention.size=512MB"
      - "--storage.tsdb.path=/etc/prometheus/prometheus"
    container_name: prometheus
#    deploy:
#      resources:
#        limits:
#          cpus: 0.15
#          memory: 120M
#        reservations:
#          cpus: 0.10
#          memory: 80M