version: '3'
services:
  nginx:
    image: nginx:1.19-alpine
    networks:
      - edge
    volumes:
      - ./nginx/certs:/data/nginx/certs
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
  spring-boot:
    image: "aghimagemanager/image_manager"
    expose:
      - "8080"
    container_name: spring-boot
    restart: always
    volumes:
      - /logs:/logs
      - /dump:/dump
      - /data:/data
    environment:
      - SPRING_PROFILES_ACTIVE=abc
      - JAVA_OPTS=-Xloggc:/data/gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dump
    networks:
      - edge

networks:
  edge: {}