version: '3'
services:
  nginx:
    image: nginx:1.19-alpine
    network_mode: host
    volumes:
      - ./certs:/data/nginx/certs
      - ./nginx:/etc/nginx/conf.d
  spring-boot:
    image: "aghimagemanager/image_manager"
    ports:
      - "8080:8080"
    container_name: spring-boot
    restart: always
    volumes:
      - /logs:/logs
      - /dump:/dump
      - /data:/data
    environment:
      - SPRING_PROFILES_ACTIVE=abc
      - JAVA_OPTS=-Xloggc:/data/gc.log -Dclient.maxInMemorySize=8 -Xmx256m -XX:MaxDirectMemorySize=256m -Dio.netty.maxDirectMemory=0
    networks:
      - edge
  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    ports:
      - 9100:9100
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
    container_name: node-exporter

networks:
  edge: {}