version: '3'
services:
  nginx:
    image: nginx:1.19-alpine
    network_mode: host
    volumes:
      - ./certs:/data/nginx/certs
      - ./nginx:/etc/nginx/conf.d
  load-balancer:
    image: "aghimagemanager/image_manager:load-balancer"
    container_name: load-balancer
    ports:
      - "8080:8080"
    restart: always
    environment:
      - JAVA_OPTS=