version: '3'
services:
  nginx:
    image: nginx:1.19-alpine
    network_mode: host
    volumes:
      - ./certs:/data/nginx/certs
      - ./nginx:/etc/nginx/conf.d
  load-balancer:
    image: "aghimagemanager/image_manager:load-balancer"
    container_name: load-balancer
    ports:
      - "8080:8080"
    restart: always
    environment:
      - JAVA_OPTS=-Xmx256m -XX:MaxDirectMemorySize=256m -Dio.netty.maxDirectMemory=0 -Dclient.maxInMemorySize=8 -Dclient.maxConnections=100 -Dclient.pendingAcquireTimeout=60 -Dclient.pendingAcquireMaxCount=1000
  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    ports:
      - 9100:9100
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
    container_name: node-exporter