origins:
  hosts:
    - url: 10.0.0.102
      maxConcurrentConnections: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

  metrics:
    web:
      server:
        request:
          autotime:
            percentiles:
              - 0.5
              - 0.9
              - 0.99

spring:
  cache:
    type: redis

  redis:
    host: local_redis
    port: 6379
