origins:
  hosts:
    - url: a.com
      maxConcurrentConnections: 50
    - url: b.com
      maxConcurrentConnections: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

  metrics:
    export.prometheus.enabled: true
    web:
      server:
        request:
          autotime:
            percentiles:
              - 0.5
              - 0.9
              - 0.99

spring:
  cache:
    jcache:
      config: ehcache.xml

logging:
  file:
    name: /logs