origins:
  hosts:
    - url: origin-server.herokuapp.com
      maxConcurrentConnections: 10
    - url: origin-server2.herokuapp.com
      maxConcurrentConnections: 10
    - url: 3.231.123.48
      maxConcurrentConnections: 10
    
#Uncomment to see persistent connections output https://www.javaer101.com/en/article/34147137.html
#
#logging:
#  level:
#    reactor:
#      netty: debug