origins:
  hosts:
    - hostname: origin-server.herokuapp.com
      ip: origin-server.herokuapp.com
      maxConcurrentConnections: 10
    - hostname: origin-server2.herokuapp.com
      ip: origin-server2.herokuapp.com
      maxConcurrentConnections: 10
    - hostname: a.com
      ip: 3.231.123.48
      maxConcurrentConnections: 10
    - hostname: b.com
      ip: 3.231.123.48
      maxConcurrentConnections: 10

spring:
  cache:
    jcache:
      config: ehcache-local-2.xml

server:
  port: 12000
    
#Uncomment to see persistent connections output https://www.javaer101.com/en/article/34147137.html
#
#logging:
#  level:
#    reactor:
#      netty: debug