origins:
  hosts:
    - hostname: origin-server.herokuapp.com
      ip: origin-server.herokuapp.com
      maxConcurrentConnections: 10
    - hostname: origin-server2.herokuapp.com
      ip: origin-server2.herokuapp.com
      maxConcurrentConnections: 10