global:
  scrape_interval:     10s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 10s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'reactive-spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-boot:8080']

remote_write:
  - url: https://aghimagemanager.grafana.net/api/prom/push
    basic_auth:
      username: ${{ secrets.GRAFANA_USERNAME }}
      password: ${{ secrets.GRAFANA_PASSWORD }}
