{
 "title": "ImageManagerMetrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/{fileName}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Percentile successful",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.5\", uri=\"/{fileName}\", status=~\"2.+\"}) by (uri,quantile)",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.9\", uri=\"/{fileName}\", status=~\"2.+\"}) by (uri,quantile)",
     "legendFormat": "P90"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.99\", uri=\"/{fileName}\", status=~\"2.+\"}) by (uri,quantile)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AVG",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{uri=\"/{fileName}\"}[2m])) / sum(increase(http_server_requests_seconds_count{uri=\"/{fileName}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Percentile failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.5\", uri=\"/{fileName}\", status=~\"[4,5].+\"}) by (uri,quantile)",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.9\", uri=\"/{fileName}\", status=~\"[4,5].+\"}) by (uri,quantile)",
     "legendFormat": "P90"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.99\", uri=\"/{fileName}\", status=~\"[4,5].+\"}) by (uri,quantile)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Percentile all",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.5\", uri=\"/{fileName}\", status=~\"2.+\"}) by (uri,quantile)",
     "legendFormat": "p50"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.9\", uri=\"/{fileName}\", status=~\"2.+\"}) by (uri,quantile)",
     "legendFormat": "p90"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile =~ \"0.99\", uri=\"/{fileName}\", status=~\"2.+\"}) by (uri,quantile)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{uri=\"/{fileName}\"}[2m]))",
     "legendFormat": "All requests"
    },
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{uri=\"/{fileName}\", status=~\"2.+\"}[2m]))",
     "legendFormat": "Successful requests"
    },
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{uri=\"/{fileName}\", status=~\"[4,5].+\"}[2m]))",
     "legendFormat": "Failed requests"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Outbound traffic [Bytes/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(edge_outbound_traffic_size_bytes_sum[5m])",
     "legendFormat": "Outbound traffic [Bytes/s]"
    }
   ]
  },
  {
   "title": "Inbound traffic [Bytes/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(origin_inbound_traffic_size_bytes_sum[5m])",
     "legendFormat": "Inbound traffic [Bytes/s]"
    }
   ]
  },
  {
   "title": "Cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_cache_miss_total", "legendFormat": "Cache misses" }
   ]
  }
 ]
}