apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://127.0.0.1:9090
    jsonData:
      httpMode: GET
      timeInterval: 5s