edge:
  clients-ips:
    - "http://10.0.0.101:8080"
    - "http://10.0.0.103:8080"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

  metrics:
    export.prometheus.enabled: true